### ISSUE TITLE
Message text not editable

### ISSUE THREAD

**Issue by webaff** [adrianbj/PageProtector#1]
Changes to the text inside the Message field (Admin > Modules > Page Protector) has no effect to the login screen (PW 2.8.23).

**Comment by adrianbj** [comment]
@webaff - does this help: https://processwire.com/talk/topic/8387-page-protector/?do=findComment&comment=110277

That setting is just the default - changes to it won't overwrite the message for already protected pages.

**Comment by webaff** [comment]
> The message on the module settings page should populate newly added protected pages, but once a page has been protected, it stores its custom message separately.

@adrianbj – Yep, this helps a lot! Thanks for your support.

**Comment by adrianbj** [comment]
Ok, great - I'll close now as it sounds like you have things working now as expected, but please re-open if  you still have problems.
