### ISSUE TITLE
Redirects to parent page

### ISSUE THREAD

**Issue by gmclelland** [adrianbj/PageProtector#2]
Hi there,

I was testing this module and noticed a problem.  If I protect the page /about/what to the role "bloggers" and login to that protected page with a logged out user that contains the role "blogger" , it will show the login form correctly, but after logging into that form it will redirect me to the parent page /about.

If I visit /about/what as a logged in user that contains the role "blogger", it will correctly show me the page with edit rights.

I hope that is clear.  Let me know if I can clarify more.  I tried protecting two different pages and it did the same thing on each page.

I'm running PW 3.0.37 on mac with php 5.6 and Apache 2.4.

**Comment by adrianbj** [comment]
Thanks for the report @gmclelland. Can I clarify - is this specific to "bloggers" vs "blogger" or does the name of the role not matter? You mention both the singular and plural version, but just wanted to make sure one wasn't a typo.

**Comment by gmclelland** [comment]
Correct.  The name of the role doesn't matter.

**Comment by adrianbj** [comment]
Can you see what happens if you comment out this line:
https://github.com/adrianbj/PageProtector/blob/master/PageProtector.module#L249

**Comment by adrianbj** [comment]
Or is there any chance you have a hook that redirects to the parent page after login?

**Comment by gmclelland** [comment]
I tried commenting that line, but it still didn't work.

> Or is there any chance you have a hook that redirects to the parent page after login?

Not that I know of.

Here are the modules I'm using:
AdminModalception
AdminOnSteriods
BatchChildEditor
CroppableImage3
FieldtypeAssistedURL
PageReferencesTab
ProcessSelectorTest
ProcessSetupPageName
ProcessWireUpgrade
TracyDebugger

Hope that helps

**Comment by gmclelland** [comment]
Hmmm... When viewing a protected page as a logged out anonymous user, I'm not sure the login form is checking the username and password either.

I entered test in the username field and test in password field and it redirected me to the protected page's parent page.

Does this happen for you?

**Comment by gmclelland** [comment]
I think I found the problem.  I'll send a pull request in little bit.

**Comment by gmclelland** [comment]
Well I thought I found the problem, but I'm not sure how best to fix it.

Basically I noticed if you remove the "./" on line 257 at 
`<form class='PageProtectorForm' action='./' method='post'>`
it will redirect to the correct page.

Some suggest to set it to:
`action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>"`

If you set to "", the form won't validate.

It probably needs to be set to the page->url, but the whole login form is in a variable and I'm not sure how to echo the page url inside.

The form does seem to check the credentials properly, but it probably needs an error message like "Login failed.  Please try again." if you enter the wrong credentials.  Right now, it just shows the form again if you enter the wrong credentials.

Hope that helps

**Comment by adrianbj** [comment]
Thanks so much for tracking this down - I am not sure why I got into the habit of using `./` for form actions. It has been working fine for me (and it seems most users), but I will certainly sort this out. `$_SERVER['PHP_SELF']` won't actually work because of the mod_rewrite rules that PW uses with its friendly URLs, but I can use `$_SERVER['REQUEST_URI']`

I'll try to get this change committed sometime today.

**Comment by adrianbj** [comment]
Please try the latest version. I have fixed the redirect issue and added a translatable Login Failed message. Please test and close this issue if everything seems to be working ok.

Thanks again for your help with this.

**Comment by gmclelland** [comment]
That worked!  Thank you for the quick fix.  Glad I could help.
